import { type NextPage } from "next";

import Head from "next/head";
import { Alert } from "~/components/Alert";

import { Content } from "~/components/Content";
import { Footer } from "~/components/Footer";
import { Header } from "~/components/Header";

import { AlertContextProvider } from "~/store/alertStore";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Note taker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ minHeight: '100vh', position: 'relative'}}>
        <Header />
        <AlertContextProvider>
          <Content />
          <Alert />
        </AlertContextProvider>
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
};

export default Home;

